language: java

jdk:
- openjdk8
- openjdk11
- openjdk17

addons:
  apt:
    packages:
    - libxml2-utils

before_install:
- source ./src/ci/before_install.sh

# skip the Travis-CI install phase because Maven handles that directly
install:
- "true"

script:
- "./src/ci/build.sh"

after_failure:
# debugging failsafe tests
- cat integration-tests/target/failsafe-reports/*IT.txt
- cat integration-tests/target/failsafe-reports/*dump*
