version: 2.1

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.322
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: java -version
      - run:
          name: Build
          command: ./mvnw clean install -Pci
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.13
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: java -version
      - run:
          name: Build
          command: ./mvnw clean install -Pci        
  
  jdk17:
    docker:
      - image: cimg/openjdk:17.0.3
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: java -version
      - run:
          name: Build
          command: ./mvnw clean install -Pci 

workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
      - jdk17
