version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.3
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./src/ci/build.sh

workflows:
  build_and_test:
    jobs:
      - build
