version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.292
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: java --version
      - run:
          name: Build
          command: ./mvnw -e -X clean install -Pci 

workflows:
  build_and_test:
    jobs:
      - build
