version: 2.1

aliases:
  - &env
    - environment:
        JVM_OPTS: -Xmx3200m
  - &go
    - checkout
    - run: java -version
    - run: ./mvnw clean install -Pci
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*IT.txt
    - run:
        when: on_fail
        command: cat integration-tests/target/failsafe-reports/*dump*

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.322
    environment: *env
    steps: *go
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.13
    environment: *env
    steps: *go
          
  jdk17:
    docker:
      - image: cimg/openjdk:17.0.3
    environment: *env
    steps: *go

workflows:
  build_and_test:
    jobs:
      - jdk8
      - jdk11
      - jdk17
